name: Deploy static site with git pull via bastion

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Git pull on remote server via bastion
        run: |
          ssh -o StrictHostKeyChecking=no -o ProxyJump=${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /var/www/html
            git pull origin main
          EOF