name: Deploy via Bastion

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to web server via bastion
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_IP }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ssh -o StrictHostKeyChecking=no azureuser@10.0.1.4 << 'EOF'
              cd /var/www/html
              git pull origin main
              sudo systemctl reload ngnix
            EOF

