name: Deploy via Bastion

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_PRIVATE_KEY }}" > ~/.ssh/id_bastion
        echo "${{ secrets.APP_SERVER_PRIVATE_KEY }}" > ~/.ssh/id_app
        chmod 600 ~/.ssh/id_bastion ~/.ssh/id_app

        printf "Host bastion\n  HostName ${{ secrets.BASTION_IP }}\n  User ${{ secrets.BASTION_USERNAME }}\n  IdentityFile ~/.ssh/id_bastion\n  StrictHostKeyChecking no\n\nHost webserver\n  HostName ${{ secrets.APP_SERVER_IP }}\n  User ${{ secrets.APP_SERVER_USERNAME }}\n  IdentityFile ~/.ssh/id_app\n  ProxyJump bastion\n  StrictHostKeyChecking no\n" > ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Deploy to webserver
      run: |
        ssh webserver << 'EOF'
          cd /var/www/html
          git pull origin main
          sudo systemctl reload nginx
        EOF
